TRUNCATE TABLE patient;
TRUNCATE TABLE invoice;
TRUNCATE TABLE patient_bed_mapping;
TRUNCATE TABLE approved_discount;
TRUNCATE TABLE ot;
TRUNCATE TABLE ot_details;
TRUNCATE TABLE patient_services;
TRUNCATE TABLE general_complain;
TRUNCATE TABLE doctor;
